######################################################################
# Automatically generated by qmake (3.0) jue. oct. 12 22:35:04 2017
######################################################################

TEMPLATE = app
TARGET = testIA
INCLUDEPATH += .

# Input
HEADERS += ai.h board.h
SOURCES += ai.cpp board.cpp test.cpp

FLAGS += -g